### PR TITLE
FIX + fixed bug with amount of excel columns that could be read in

### PR DESCRIPTION
**Pull request by tomasz-misiak**
fixed bug with amount of excel columns that could be read in
single sheet, added classpath and project, just to have identical
project structure as is in google.code

### CODE REVIEW

**Comment by tougar** [comment]
good point!

**Comment by opticyclic** [comment]
Can you change you pull request so that it only contains the bug fix?
At the moment it looks like you have changed every line in the file (maybe code formatting differences).

Also, you shouldn't add eclipse files because:
a) it is not relevant to this pull request
b) the pom file is enough to describe the project

**Review by davidpelfree — CHANGES_REQUESTED** [review]
As @opticyclic commented, please:
1. fix the indentation issue so that everyone can clearly see what is your change.
2. Remove Eclipse specific files. They could be automatically generated from pom.xml and they usually contains user-specific info (local paths, etc.) - in short: they should not be in Git.

**Comment by mahendranchinnaiah** [comment]
Dear All,
I have used the jar from https://code.google.com/archive/p/sjxslx/downloads to work on huge Excel. But am getting only 52 columns while reading from the excel. Here i can see that issues got fixed. Basically am from .Net background and i am getting stuck how to use this source. Could you pls  anyone share me the jar from this updated source and sample functions to read and write from the excel. I am wasting more than a week for this activity. It would be very helpful if anyone shared this..

**Pull request closed without merging**
